import dynamic from "next/dynamic";
import type { Metadata } from "next";
import { Jura } from "next/font/google";
import "./globals.css";
import Providers from "@/hooks/providers";
import ToasterContext from "@/context/ToasterContext";

const inter = Jura({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Navbar = dynamic(() => import("../components/Navbar"), { ssr: false });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ToasterContext />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
